In [1]:
from buildstock_query import BuildStockQuery
import pandas as pd
import polars as pl

In [2]:
# auto reload
%load_ext autoreload
%autoreload 2

In [6]:
res_run = BuildStockQuery('rescore','buildstock_sdr',
                        "resstock_2024_amy2018_release_2",
                        buildstock_type='resstock',
                        db_schema="resstock_oedi",
                        skip_reports=False)

INFO:buildstock_query.query_core:Loading resstock_2024_amy2018_release_2 ...
INFO:botocore.tokens:Loading cached SSO token for nrel-sso
INFO:buildstock_query.query_core:14 queries cache read from .bsq_cache/resstock_2024_amy2018_release_2_query_cache.pkl.
INFO:buildstock_query.query_core:14 queries cache is updated.
INFO:buildstock_query.main:Getting Success counts...
INFO:botocore.tokens:Loading cached SSO token for nrel-sso
INFO:botocore.tokens:Loading cached SSO token for nrel-sso
INFO:buildstock_query.report_query:Checking integrity with ts_tables ...

         success  inapplicable  fail     Sum  Applied %  no-chng  bad-chng  \
upgrade
0         549718             0     0  549718        0.0      0.0       0.0
1         528643         21075     0  549718       96.2      8.0   14690.0
10        406046        143672     0  549718       73.9      2.0    5230.0
11        528642         21076     0  549718       96.2      0.0    4329.0
12        528641         21077     0  549718       96.2      1.0    3484.0
13        528641         21077     0  549718       96.2      0.0    3032.0
14        268775        280943     0  549718       48.9      0.0     100.0
15        406029        143689     0  549718       73.9      0.0    1865.0
16        445283        104435     0  549718       81.0    981.0    2258.0
2         528642         21076     0  549718       96.2     10.0   12863.0
3         528641         21077     0  549718       96.2      4.0   11606.0
4         268777        280941     0  549718       48.9      1.0    1735.0
5         406018        143700     0  549718       73.9      4.0    6068.0
6         528640         21078     0  549718       96.2      3.0   13318.0
7         528641         21077     0  549718       96.2      5.0   11906.0
8         528641         21077     0  549718       96.2      2.0   10888.0
9         268775        280943     0  549718       48.9      0.0    1659.0

          ok-chng  true-bad-chng  true-ok-chng  null       any  no-chng %  \
upgrade
0             0.0            0.0           0.0   0.0       0.0        0.0
1        513945.0        14690.0      513945.0   0.0  528643.0        0.0
10       400814.0         5230.0      400814.0   0.0  406046.0        0.0
11       524313.0         4329.0      524313.0   0.0  528642.0        0.0
12       525156.0         3484.0      525156.0   0.0  528641.0        0.0
13       525609.0         3032.0      525609.0   0.0  528641.0        0.0
14       268675.0          100.0      268675.0   0.0  268775.0        0.0
15       404164.0         1865.0      404164.0   0.0  406029.0        0.0
16       442044.0         2258.0      442044.0   0.0  445283.0        0.2
2        515769.0        12863.0      515769.0   0.0  528642.0        0.0
3        517031.0        11606.0      517031.0   0.0  528641.0        0.0
4        267041.0         1735.0      267041.0   0.0  268777.0        0.0
5        399946.0         6068.0      399946.0   0.0  406018.0        0.0
6        515319.0        13318.0      515319.0   0.0  528640.0        0.0
7        516730.0        11906.0      516730.0   0.0  528641.0        0.0
8        517751.0        10888.0      517751.0   0.0  528641.0        0.0
9        267116.0         1659.0      267116.0   0.0  268775.0        0.0

         bad-chng %  ok-chng %  true-ok-chng %  true-bad-chng %
upgrade
0               0.0        0.0             0.0              0.0
1               2.8       97.2            97.2              2.8
10              1.3       98.7            98.7              1.3
11              0.8       99.2            99.2              0.8
12              0.7       99.3            99.3              0.7
13              0.6       99.4            99.4              0.6
14              0.0      100.0           100.0              0.0
15              0.5       99.5            99.5              0.5
16              0.5       99.3            99.3              0.5
2               2.4       97.6            97.6              2.4
3               2.2       97.8            97.8              2.2
4               0.6       99.4            99.4              0.6
5               1.5       98.5            98.5              1.5
6               2.5       97.5            97.5              2.5
7               2.3       97.7            97.7              2.3
8               2.1       97.9            97.9              2.1
9               0.6       99.4            99.4              0.6

INFO:buildstock_query.query_core:{'submitted': 0, 'running': 0, 'pending': 17, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:Submitted queries[0] (27ba7c05-269d-4b18-b88f-ec05cd1d0b93)
INFO:buildstock_query.query_core:Submitted queries[1] (a8288503-f890-4f19-b792-b12cfedcbe76)
INFO:buildstock_query.query_core:{'submitted': 2, 'running': 1, 'pending': 16, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:Submitted queries[2] (e0273e91-68c2-4aa0-949c-1764ae3fecb5)
INFO:buildstock_query.query_core:Submitted queries[3] (bd860812-7da8-448e-a444-4e8978b99ee1)
INFO:buildstock_query.query_core:{'submitted': 4, 'running': 4, 'pending': 13, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:{'submitted': 4, 'running': 4, 'pending': 13, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:{'submitted': 4, 'running': 4, 'pending': 13, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:{'submitted': 4, 'running': 4, 'pending': 13, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:{'submitted': 4, 'running': 4, 'pending': 13, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:{'submitted': 4, 'running': 4, 'pending': 13, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:{'submitted': 4, 'running': 4, 'pending': 13, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:{'submitted': 4, 'running': 4, 'pending': 13, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:Submitted queries[4] (3446af6b-467e-4b75-bcce-59a621fd68ee)
INFO:buildstock_query.query_core:Submitted queries[5] (c14a697b-cfe2-403f-a2cf-36243ff32799)
INFO:buildstock_query.query_core:{'submitted': 6, 'running': 3, 'pending': 11, 'completed': 0, 'failed': 3}
INFO:buildstock_query.query_core:Submitted queries[6] (9441b2e8-53c7-4a5c-a5b5-36ed2a76eaac)
INFO:buildstock_query.query_core:{'submitted': 7, 'running': 4, 'pending': 10, 'completed': 0, 'failed': 3}
INFO:buildstock_query.query_core:{'submitted': 7, 'running': 4, 'pending': 10, 'completed': 0, 'failed': 3}
INFO:buildstock_query.query_core:Submitted queries[7] (3a7aea29-9bab-4db0-a04b-ef8131c89eb4)
INFO:buildstock_query.query_core:{'submitted': 8, 'running': 4, 'pending': 9, 'completed': 0, 'failed': 4}
INFO:buildstock_query.query_core:Submitted queries[8] (2ef39f14-04db-4c6b-9a6d-f570826048c2)
INFO:buildstock_query.query_core:{'submitted': 9, 'running': 4, 'pending': 8, 'completed': 0, 'failed': 5}
INFO:buildstock_query.query_core:{'submitted': 9, 'running': 4, 'pending': 8, 'completed': 0, 'failed': 5}
INFO:buildstock_query.query_core:{'submitted': 9, 'running': 4, 'pending': 8, 'completed': 0, 'failed': 5}
INFO:buildstock_query.query_core:{'submitted': 9, 'running': 3, 'pending': 8, 'completed': 0, 'failed': 6}
INFO:buildstock_query.query_core:Submitted queries[9] (80d43091-7acb-401e-b316-0d9a372f2b4c)
INFO:buildstock_query.query_core:{'submitted': 10, 'running': 4, 'pending': 7, 'completed': 0, 'failed': 6}
INFO:buildstock_query.query_core:Submitted queries[10] (4a2191c0-8ff2-4738-8702-b6fa3fa23f11)
INFO:buildstock_query.query_core:{'submitted': 11, 'running': 4, 'pending': 6, 'completed': 0, 'failed': 7}
INFO:buildstock_query.query_core:{'submitted': 11, 'running': 4, 'pending': 6, 'completed': 0, 'failed': 7}
INFO:buildstock_query.query_core:{'submitted': 11, 'running': 4, 'pending': 6, 'completed': 0, 'failed': 7}
INFO:buildstock_query.query_core:{'submitted': 11, 'running': 4, 'pending': 6, 'completed': 0, 'failed': 7}
INFO:buildstock_query.query_core:Submitted queries[11] (4e421697-c54a-4120-8a29-3a4ca0f4b598)
INFO:buildstock_query.query_core:{'submitted': 12, 'running': 4, 'pending': 5, 'completed': 0, 'failed': 8}
INFO:buildstock_query.query_core:{'submitted': 12, 'running': 4, 'pending': 5, 'completed': 0, 'failed': 8}
INFO:buildstock_query.query_core:{'submitted': 12, 'running': 4, 'pending': 5, 'completed': 0, 'failed': 8}
INFO:buildstock_query.query_core:{'submitted': 12, 'running': 4, 'pending': 5, 'completed': 0, 'failed': 8}
INFO:buildstock_query.query_core:Submitted queries[12] (ec6dd177-3dcf-416e-abb3-c06e4ab4873a)
INFO:buildstock_query.query_core:{'submitted': 13, 'running': 4, 'pending': 4, 'completed': 1, 'failed': 8}
INFO:buildstock_query.query_core:{'submitted': 13, 'running': 4, 'pending': 4, 'completed': 1, 'failed': 8}
INFO:buildstock_query.query_core:{'submitted': 13, 'running': 4, 'pending': 4, 'completed': 1, 'failed': 8}
INFO:buildstock_query.query_core:{'submitted': 13, 'running': 4, 'pending': 4, 'completed': 1, 'failed': 8}
INFO:buildstock_query.query_core:{'submitted': 13, 'running': 4, 'pending': 4, 'completed': 1, 'failed': 8}
INFO:buildstock_query.query_core:{'submitted': 13, 'running': 4, 'pending': 4, 'completed': 1, 'failed': 8}
INFO:buildstock_query.query_core:Submitted queries[13] (7467c5eb-f679-4344-a8a3-3a9c0fe7bcf8)
INFO:buildstock_query.query_core:Submitted queries[14] (4716fe1c-7d1b-4bb4-8e13-f82877f4070e)
INFO:buildstock_query.query_core:{'submitted': 15, 'running': 4, 'pending': 2, 'completed': 2, 'failed': 9}
INFO:buildstock_query.query_core:Submitted queries[15] (32e70efd-7b10-4bcb-8dbc-e469738eec67)
INFO:buildstock_query.query_core:{'submitted': 16, 'running': 4, 'pending': 1, 'completed': 3, 'failed': 9}
INFO:buildstock_query.query_core:{'submitted': 16, 'running': 4, 'pending': 1, 'completed': 3, 'failed': 9}
INFO:buildstock_query.query_core:{'submitted': 16, 'running': 4, 'pending': 1, 'completed': 3, 'failed': 9}
INFO:buildstock_query.query_core:{'submitted': 16, 'running': 4, 'pending': 1, 'completed': 3, 'failed': 9}
INFO:buildstock_query.query_core:{'submitted': 16, 'running': 4, 'pending': 1, 'completed': 3, 'failed': 9}
INFO:buildstock_query.query_core:{'submitted': 16, 'running': 4, 'pending': 1, 'completed': 3, 'failed': 9}
INFO:buildstock_query.query_core:Submitted queries[16] (44793a26-97bb-41e7-9f02-b18e8e9c6772)
INFO:buildstock_query.query_core:{'submitted': 17, 'running': 4, 'pending': 0, 'completed': 3, 'failed': 10}
INFO:buildstock_query.query_core:{'submitted': 17, 'running': 4, 'pending': 0, 'completed': 3, 'failed': 10}
INFO:buildstock_query.query_core:{'submitted': 17, 'running': 3, 'pending': 0, 'completed': 3, 'failed': 11}
INFO:buildstock_query.query_core:{'submitted': 17, 'running': 3, 'pending': 0, 'completed': 3, 'failed': 11}
INFO:buildstock_query.query_core:{'submitted': 17, 'running': 1, 'pending': 0, 'completed': 3, 'failed': 13}
INFO:buildstock_query.query_core:{'submitted': 17, 'running': 1, 'pending': 0, 'completed': 3, 'failed': 13}
INFO:buildstock_query.query_core:{'submitted': 17, 'running': 0, 'pending': 0, 'completed': 4, 'failed': 13}
INFO:buildstock_query.query_core:Batch query completed.
WARNING:buildstock_query.query_core:13 queries failed. Redoing them
INFO:buildstock_query.query_core:{'submitted': 0, 'running': 0, 'pending': 13, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:Submitted queries[0] (f1fa1721-2cdc-4d91-a139-3f274dcfcc3f)
INFO:buildstock_query.query_core:Submitted queries[1] (b677d3f8-a893-42b5-a2f5-da3545206b90)
INFO:buildstock_query.query_core:{'submitted': 2, 'running': 0, 'pending': 13, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:Submitted queries[2] (1bd9a95c-3a72-4204-8c64-9be50ab09c6d)
INFO:buildstock_query.query_core:Submitted queries[3] (1f38c017-6de1-4fa8-b94b-df6ad08f1c06)
INFO:buildstock_query.query_core:{'submitted': 4, 'running': 4, 'pending': 9, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:{'submitted': 4, 'running': 4, 'pending': 9, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:{'submitted': 4, 'running': 4, 'pending': 9, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:{'submitted': 4, 'running': 4, 'pending': 9, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:{'submitted': 4, 'running': 4, 'pending': 9, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:{'submitted': 4, 'running': 4, 'pending': 9, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:{'submitted': 4, 'running': 4, 'pending': 9, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:{'submitted': 4, 'running': 4, 'pending': 9, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:Submitted queries[4] (5143d83d-84b0-4657-bf80-f45d78fbfad8)
INFO:buildstock_query.query_core:{'submitted': 5, 'running': 3, 'pending': 8, 'completed': 0, 'failed': 2}
INFO:buildstock_query.query_core:Submitted queries[5] (7a6ba12e-ffaa-40e5-93be-5eda124884ec)
INFO:buildstock_query.query_core:{'submitted': 6, 'running': 4, 'pending': 7, 'completed': 0, 'failed': 2}
INFO:buildstock_query.query_core:{'submitted': 6, 'running': 4, 'pending': 7, 'completed': 0, 'failed': 2}
INFO:buildstock_query.query_core:{'submitted': 6, 'running': 4, 'pending': 7, 'completed': 0, 'failed': 2}
INFO:buildstock_query.query_core:Submitted queries[6] (0b829964-0aba-402e-9f77-908e69789c12)
INFO:buildstock_query.query_core:{'submitted': 7, 'running': 4, 'pending': 6, 'completed': 0, 'failed': 3}
INFO:buildstock_query.query_core:Submitted queries[7] (3719a3a4-1f33-4028-be4b-77743be1095b)
INFO:buildstock_query.query_core:{'submitted': 8, 'running': 4, 'pending': 5, 'completed': 0, 'failed': 4}
INFO:buildstock_query.query_core:{'submitted': 8, 'running': 4, 'pending': 5, 'completed': 0, 'failed': 4}
INFO:buildstock_query.query_core:{'submitted': 8, 'running': 4, 'pending': 5, 'completed': 0, 'failed': 4}
INFO:buildstock_query.query_core:Submitted queries[8] (443fb3a2-0d8b-4d39-a26e-fc555d01d355)
INFO:buildstock_query.query_core:{'submitted': 9, 'running': 4, 'pending': 4, 'completed': 0, 'failed': 5}
INFO:buildstock_query.query_core:{'submitted': 9, 'running': 4, 'pending': 4, 'completed': 0, 'failed': 5}
INFO:buildstock_query.query_core:{'submitted': 9, 'running': 4, 'pending': 4, 'completed': 0, 'failed': 5}
INFO:buildstock_query.query_core:{'submitted': 9, 'running': 4, 'pending': 4, 'completed': 0, 'failed': 5}
INFO:buildstock_query.query_core:Submitted queries[9] (c00f5562-678d-4fd4-bf24-419fce6826ce)
INFO:buildstock_query.query_core:{'submitted': 10, 'running': 4, 'pending': 3, 'completed': 1, 'failed': 5}
INFO:buildstock_query.query_core:Submitted queries[10] (9f6b1547-da1f-45b6-9d18-c19d6e53c71d)
INFO:buildstock_query.query_core:{'submitted': 11, 'running': 3, 'pending': 2, 'completed': 3, 'failed': 5}
INFO:buildstock_query.query_core:Submitted queries[11] (eb1e29d6-91ac-43c0-a3fd-db0dcb1424e7)
INFO:buildstock_query.query_core:{'submitted': 12, 'running': 4, 'pending': 1, 'completed': 3, 'failed': 5}
INFO:buildstock_query.query_core:Submitted queries[12] (c4ffef75-2b51-47af-b6e3-d23bc4c3c227)
INFO:buildstock_query.query_core:{'submitted': 13, 'running': 4, 'pending': 0, 'completed': 4, 'failed': 5}
INFO:buildstock_query.query_core:{'submitted': 13, 'running': 4, 'pending': 0, 'completed': 4, 'failed': 5}
INFO:buildstock_query.query_core:{'submitted': 13, 'running': 4, 'pending': 0, 'completed': 4, 'failed': 5}
INFO:buildstock_query.query_core:{'submitted': 13, 'running': 4, 'pending': 0, 'completed': 4, 'failed': 5}
INFO:buildstock_query.query_core:{'submitted': 13, 'running': 2, 'pending': 0, 'completed': 6, 'failed': 5}
INFO:buildstock_query.query_core:{'submitted': 13, 'running': 2, 'pending': 0, 'completed': 6, 'failed': 5}
INFO:buildstock_query.query_core:{'submitted': 13, 'running': 1, 'pending': 0, 'completed': 7, 'failed': 5}
INFO:buildstock_query.query_core:{'submitted': 13, 'running': 0, 'pending': 0, 'completed': 8, 'failed': 5}

Query id: f1fa1721-2cdc-4d91-a139-3f274dcfcc3f.
 Query string: SELECT '0' AS upgrade, count(distinct(resstock_2024_amy2018_release_2_by_state.bldg_id)) AS count
FROM resstock_2024_amy2018_release_2_by_state
WHERE CAST(resstock_2024_amy2018_release_2_by_state.upgrade AS VARCHAR) = '0'. Query Ended with: FAILED
Error: HIVE_S3_THROTTLING: S3 throttling

Query id: b677d3f8-a893-42b5-a2f5-da3545206b90.
 Query string: SELECT '1' AS upgrade, count(distinct(resstock_2024_amy2018_release_2_by_state.bldg_id)) AS count
FROM resstock_2024_amy2018_release_2_by_state
WHERE CAST(resstock_2024_amy2018_release_2_by_state.upgrade AS VARCHAR) = '1'. Query Ended with: FAILED
Error: HIVE_S3_THROTTLING: S3 throttling

Query id: 1bd9a95c-3a72-4204-8c64-9be50ab09c6d.
 Query string: SELECT '2' AS upgrade, count(distinct(resstock_2024_amy2018_release_2_by_state.bldg_id)) AS count
FROM resstock_2024_amy2018_release_2_by_state
WHERE CAST(resstock_2024_amy2018_release_2_by_state.upgrade AS VARCHAR) = '2'. Query Ended with: FAILED
Error: HIVE_S3_THROTTLING: S3 throttling

Query id: 1f38c017-6de1-4fa8-b94b-df6ad08f1c06.
 Query string: SELECT '3' AS upgrade, count(distinct(resstock_2024_amy2018_release_2_by_state.bldg_id)) AS count
FROM resstock_2024_amy2018_release_2_by_state
WHERE CAST(resstock_2024_amy2018_release_2_by_state.upgrade AS VARCHAR) = '3'. Query Ended with: FAILED
Error: HIVE_S3_THROTTLING: S3 throttling

Query id: 5143d83d-84b0-4657-bf80-f45d78fbfad8.
 Query string: SELECT '4' AS upgrade, count(distinct(resstock_2024_amy2018_release_2_by_state.bldg_id)) AS count
FROM resstock_2024_amy2018_release_2_by_state
WHERE CAST(resstock_2024_amy2018_release_2_by_state.upgrade AS VARCHAR) = '4'. Query Ended with: FAILED
Error: HIVE_S3_THROTTLING: S3 throttling

QueryException: Queries failed again. Sorry!

In [3]:
my_run = BuildStockQuery('rescore','buildstock_sdr',
                        "comstock_amy2018_r2_2025",
                        buildstock_type='comstock',
                        db_schema="comstock_oedi_state_and_county",
                        skip_reports=False)

INFO:buildstock_query.query_core:Loading comstock_amy2018_r2_2025 ...

INFO:botocore.tokens:Loading cached SSO token for nrel-sso
INFO:botocore.tokens:SSO Token refresh succeeded
INFO:buildstock_query.query_core:145 queries cache read from .bsq_cache/comstock_amy2018_r2_2025_query_cache.pkl.
INFO:buildstock_query.query_core:145 queries cache is updated.
INFO:buildstock_query.main:Getting Success counts...
INFO:buildstock_query.report_query:Checking integrity with ts_tables ...
INFO:buildstock_query.query_core:Submitted queries[0] (CACHED)
INFO:buildstock_query.query_core:{'submitted': 0, 'running': 0, 'pending': 62, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:Submitted queries[1] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[2] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[3] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[4] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[5] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[6] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[7] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[8] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[9] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[10] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[11] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[12] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[13] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[14] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[15] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[16] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[17] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[18] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[19] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[20] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[21] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[22] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[23] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[24] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[25] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[26] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[27] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[28] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[29] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[30] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[31] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[32] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[33] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[34] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[35] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[36] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[37] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[38] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[39] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[40] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[41] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[42] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[43] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[44] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[45] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[46] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[47] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[48] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[49] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[50] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[51] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[52] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[53] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[54] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[55] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[56] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[57] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[58] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[59] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[60] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[61] (CACHED)

           success  inapplicable  fail        Sum  Applied %  no-chng  \
upgrade
0        7602151.0           0.0     0  7602151.0        0.0      0.0
1        4257229.0     3344922.0     0  7602151.0       56.0      0.0
10       4257064.0     3345087.0     0  7602151.0       56.0      0.0
11       4053004.0     3549147.0     0  7602151.0       53.3      0.0
12       4052904.0     3549247.0     0  7602151.0       53.3      0.0
...            ...           ...   ...        ...        ...      ...
60       7274170.0      327981.0     0  7602151.0       95.7     47.0
61       7602128.0          23.0     0  7602151.0      100.0   5269.0
7        4256950.0     3345201.0     0  7602151.0       56.0      0.0
8        4257231.0     3344920.0     0  7602151.0       56.0      0.0
9        4256914.0     3345237.0     0  7602151.0       56.0      0.0

         bad-chng    ok-chng  true-bad-chng  true-ok-chng  null        any  \
upgrade
0             0.0        0.0            0.0           0.0   0.0        0.0
1           131.0  4257098.0          131.0     4257098.0   0.0  4257229.0
10            0.0  4257064.0            0.0     4257064.0   0.0  4257064.0
11           37.0  4052967.0           37.0     4052967.0   0.0  4053004.0
12           37.0  4052867.0           37.0     4052867.0   0.0  4052904.0
...           ...        ...            ...           ...   ...        ...
60       106943.0  7167180.0       106943.0     7167180.0   0.0  7274170.0
61        10187.0  7586672.0        10187.0     7586672.0   0.0  7602128.0
7          1850.0  4255100.0         1850.0     4255100.0   0.0  4256950.0
8         37769.0  4219462.0        37769.0     4219462.0   0.0  4257231.0
9          3321.0  4253593.0         3321.0     4253593.0   0.0  4256914.0

         no-chng %  bad-chng %  ok-chng %  true-ok-chng %  true-bad-chng %
upgrade
0              0.0         0.0        0.0             0.0              0.0
1              0.0         0.0      100.0           100.0              0.0
10             0.0         0.0      100.0           100.0              0.0
11             0.0         0.0      100.0           100.0              0.0
12             0.0         0.0      100.0           100.0              0.0
...            ...         ...        ...             ...              ...
60             0.0         1.5       98.5            98.5              1.5
61             0.1         0.1       99.8            99.8              0.1
7              0.0         0.0      100.0           100.0              0.0
8              0.0         0.9       99.1            99.1              0.9
9              0.0         0.1       99.9            99.9              0.1

[62 rows x 17 columns]

INFO:buildstock_query.query_core:{'submitted': 62, 'running': 0, 'pending': 0, 'completed': 62, 'failed': 0}
INFO:buildstock_query.query_core:Batch query completed.
INFO:buildstock_query.query_core:Got result from Query [0] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [1] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [2] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [3] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [4] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [5] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [6] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [7] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [8] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [9] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [10] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [11] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [12] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [13] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [14] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [15] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [16] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [17] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [18] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [19] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [20] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [21] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [22] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [23] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [24] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [25] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [26] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [27] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [28] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [29] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [30] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [31] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [32] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [33] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [34] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [35] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [36] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [37] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [38] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [39] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [40] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [41] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [42] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [43] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [44] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [45] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [46] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [47] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [48] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [49] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [50] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [51] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [52] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [53] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [54] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [55] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [56] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [57] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [58] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [59] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [60] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [61] (CACHED)
INFO:buildstock_query.query_core:Concatenating the results.
INFO:buildstock_query.query_core:No new queries to save.

Baseline/upgrade and timeseries tables have matching distinct building counts.
No duplicate rows in baseline table on ['bldg_id', 'in.nhgis_tract_gisjoin', 'state'].
No duplicate rows in upgrade table on ['bldg_id', 'in.nhgis_tract_gisjoin', 'state', 'upgrade'].
All building partitions have the same number of (35040) timeseries rows.

In [4]:
report_df = my_run.report.get_success_report()
report_df.sort_values('bad-chng %', ascending=False, inplace=True)
report_df.to_csv("comstock_upgrade_results.csv")
report_df

,success,inapplicable,fail,Sum,Applied %,no-chng,bad-chng,ok-chng,true-bad-chng,true-ok-chng,null,any,no-chng %,bad-chng %,ok-chng %,true-ok-chng %,true-bad-chng %
upgrade,,,,,,,,,,,,,,,,,
38,7474082.0,128069.0,0,7602151.0,98.3,4245.0,7404789.0,65048.0,7404789.0,65048.0,0.0,7474082.0,0.1,99.1,0.9,0.9,99.1
29,3474227.0,4127924.0,0,7602151.0,45.7,77199.0,3332879.0,64149.0,3332879.0,64149.0,0.0,3474227.0,2.2,95.9,1.8,1.8,95.9
37,6229122.0,1373029.0,0,7602151.0,81.9,67406.0,5656507.0,505209.0,5656507.0,505209.0,0.0,6229122.0,1.1,90.8,8.1,8.1,90.8
26,1611444.0,5990707.0,0,7602151.0,21.2,0.0,558385.0,1053059.0,558385.0,1053059.0,0.0,1611444.0,0.0,34.7,65.3,65.3,34.7
47,7565905.0,36246.0,0,7602151.0,99.5,8816.0,1103454.0,6453635.0,1103454.0,6453635.0,0.0,7565905.0,0.1,14.6,85.3,85.3,14.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30,3546153.0,4055998.0,0,7602151.0,46.6,0.0,494.0,3545659.0,494.0,3545659.0,0.0,3546153.0,0.0,0.0,100.0,100.0,0.0
33,3528558.0,4073593.0,0,7602151.0,46.4,61.0,800.0,3527697.0,800.0,3527697.0,0.0,3528558.0,0.0,0.0,100.0,100.0,0.0
1,4257229.0,3344922.0,0,7602151.0,56.0,0.0,131.0,4257098.0,131.0,4257098.0,0.0,4257229.0,0.0,0.0,100.0,100.0,0.0
40,7602148.0,3.0,0,7602151.0,100.0,0.0,772.0,7601376.0,772.0,7601376.0,0.0,7602148.0,0.0,0.0,100.0,100.0,0.0
0,7602151.0,0.0,0,7602151.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
# folder_path = my_run.download_metadata_and_annual_results(
#     upgrade_id="0",
#     folder="comstock_oedi_state_and_county"
# )
# print(folder_path)

In [6]:
from pathlib import Path
folder_path = Path("comstock_oedi_state_and_county/upgrade=0")

In [7]:
# the full set is too big to load all into memory - use polars to scan and collect only relevant columns
df = pl.scan_parquet(folder_path, hidden_file_prefix=".")
reuse_rate = (
    df.group_by("in.state")
    .agg([
        pl.len().alias("total_rows"),
        pl.col("bldg_id").n_unique().alias("distinct_bldgs")
    ])
    .with_columns(
        (pl.col("total_rows") / pl.col("distinct_bldgs")).round(2).alias("reuse_rate")
    )
    .sort("reuse_rate", descending=True)
    .collect()
)
reuse_rate

shape: (51, 4)
┌──────────┬────────────┬────────────────┬────────────┐
│ in.state ┆ total_rows ┆ distinct_bldgs ┆ reuse_rate │
│ ---      ┆ ---        ┆ ---            ┆ ---        │
│ str      ┆ u32        ┆ u32            ┆ f64        │
╞══════════╪════════════╪════════════════╪════════════╡
│ FL       ┆ 555960     ┆ 3311           ┆ 167.91     │
│ VA       ┆ 184670     ┆ 1908           ┆ 96.79      │
│ OH       ┆ 305775     ┆ 3478           ┆ 87.92      │
│ TX       ┆ 716243     ┆ 8321           ┆ 86.08      │
│ SC       ┆ 146967     ┆ 1742           ┆ 84.37      │
│ …        ┆ …          ┆ …              ┆ …          │
│ WY       ┆ 18630      ┆ 1715           ┆ 10.86      │
│ DE       ┆ 14490      ┆ 1401           ┆ 10.34      │
│ AK       ┆ 13248      ┆ 1421           ┆ 9.32       │
│ SD       ┆ 18177      ┆ 2038           ┆ 8.92       │
│ VT       ┆ 9075       ┆ 1088           ┆ 8.34       │
└──────────┴────────────┴────────────────┴────────────┘

In [8]:
reuse_rate_agg = reuse_rate.select(
    pl.col("total_rows").sum().alias("total_rows"),
    pl.col("distinct_bldgs").sum().alias("distinct_bldgs"),
    pl.col("reuse_rate").mean().alias("reuse_rate_mean"),
)
reuse_rate_agg

shape: (1, 3)
┌────────────┬────────────────┬─────────────────┐
│ total_rows ┆ distinct_bldgs ┆ reuse_rate_mean │
│ ---        ┆ ---            ┆ ---             │
│ u32        ┆ u32            ┆ f64             │
╞════════════╪════════════════╪═════════════════╡
│ 7602151    ┆ 158952         ┆ 42.974706       │
└────────────┴────────────────┴─────────────────┘

In [9]:
df.select(pl.col("bldg_id").n_unique()).collect()
# This is lower than the sum above because some bldg_ids are duplicated across states.

shape: (1, 1)
┌─────────┐
│ bldg_id │
│ ---     │
│ u32     │
╞═════════╡
│ 102678  │
└─────────┘

In [10]:
[c for c in df.collect_schema().names() if "county" in c]

['in.as_simulated_nhgis_county_gisjoin',
 'in.county_name',
 'in.nhgis_county_gisjoin',
 'county']

In [11]:
[c for c in df.collect_schema().names() if "electricity" in c]

['out.electricity.cooling.energy_consumption..kwh',
 'out.electricity.cooling.energy_savings..kwh',
 'out.electricity.exterior_lighting.energy_consumption..kwh',
 'out.electricity.exterior_lighting.energy_savings..kwh',
 'out.electricity.fans.energy_consumption..kwh',
 'out.electricity.fans.energy_savings..kwh',
 'out.electricity.heat_recovery.energy_consumption..kwh',
 'out.electricity.heat_recovery.energy_savings..kwh',
 'out.electricity.heat_rejection.energy_consumption..kwh',
 'out.electricity.heat_rejection.energy_savings..kwh',
 'out.electricity.heating.energy_consumption..kwh',
 'out.electricity.heating.energy_savings..kwh',
 'out.electricity.interior_equipment.energy_consumption..kwh',
 'out.electricity.interior_equipment.energy_savings..kwh',
 'out.electricity.interior_lighting.energy_consumption..kwh',
 'out.electricity.interior_lighting.energy_savings..kwh',
 'out.electricity.net.energy_consumption..kwh',
 'out.electricity.net.energy_savings..kwh',
 'out.electricity.pumps.energy_consumption..kwh',
 'out.electricity.pumps.energy_savings..kwh',
 'out.electricity.purchased.energy_consumption..kwh',
 'out.electricity.purchased.energy_savings..kwh',
 'out.electricity.pv.energy_consumption..kwh',
 'out.electricity.pv.energy_savings..kwh',
 'out.electricity.refrigeration.energy_consumption..kwh',
 'out.electricity.refrigeration.energy_savings..kwh',
 'out.electricity.total.apr.energy_consumption..kwh',
 'out.electricity.total.aug.energy_consumption..kwh',
 'out.electricity.total.dec.energy_consumption..kwh',
 'out.electricity.total.energy_consumption..kwh',
 'out.electricity.total.energy_savings..kwh',
 'out.electricity.total.feb.energy_consumption..kwh',
 'out.electricity.total.jan.energy_consumption..kwh',
 'out.electricity.total.jul.energy_consumption..kwh',
 'out.electricity.total.jun.energy_consumption..kwh',
 'out.electricity.total.mar.energy_consumption..kwh',
 'out.electricity.total.may.energy_consumption..kwh',
 'out.electricity.total.nov.energy_consumption..kwh',
 'out.electricity.total.oct.energy_consumption..kwh',
 'out.electricity.total.sep.energy_consumption..kwh',
 'out.electricity.water_systems.energy_consumption..kwh',
 'out.electricity.water_systems.energy_savings..kwh',
 'out.electricity.total.peak_demand..kw',
 'out.electricity.cooling.energy_consumption_intensity..kwh_per_ft2',
 'out.electricity.cooling.energy_savings_intensity..kwh_per_ft2',
 'out.electricity.exterior_lighting.energy_consumption_intensity..kwh_per_ft2',
 'out.electricity.exterior_lighting.energy_savings_intensity..kwh_per_ft2',
 'out.electricity.fans.energy_consumption_intensity..kwh_per_ft2',
 'out.electricity.fans.energy_savings_intensity..kwh_per_ft2',
 'out.electricity.heat_recovery.energy_consumption_intensity..kwh_per_ft2',
 'out.electricity.heat_recovery.energy_savings_intensity..kwh_per_ft2',
 'out.electricity.heat_rejection.energy_consumption_intensity..kwh_per_ft2',
 'out.electricity.heat_rejection.energy_savings_intensity..kwh_per_ft2',
 'out.electricity.heating.energy_consumption_intensity..kwh_per_ft2',
 'out.electricity.heating.energy_savings_intensity..kwh_per_ft2',
 'out.electricity.interior_equipment.energy_consumption_intensity..kwh_per_ft2',
 'out.electricity.interior_equipment.energy_savings_intensity..kwh_per_ft2',
 'out.electricity.interior_lighting.energy_consumption_intensity..kwh_per_ft2',
 'out.electricity.interior_lighting.energy_savings_intensity..kwh_per_ft2',
 'out.electricity.net.energy_consumption_intensity..kwh_per_ft2',
 'out.electricity.net.energy_savings_intensity..kwh_per_ft2',
 'out.electricity.pumps.energy_consumption_intensity..kwh_per_ft2',
 'out.electricity.pumps.energy_savings_intensity..kwh_per_ft2',
 'out.electricity.purchased.energy_consumption_intensity..kwh_per_ft2',
 'out.electricity.purchased.energy_savings_intensity..kwh_per_ft2',
 'out.electricity.pv.energy_consumption_intensity..kwh_per_ft2',
 'out.electricity.pv.energy_savings_intensity..kwh_per_ft2',
 'out.electricity.refrigeration.energy_consumption_intensity..kwh_per_ft2',
 'out.electricity.refrigeration.energy_savings_intensity..kwh_per_ft2',
 'out.electricity.total.energy_consumption_intensity..kwh_per_ft2',
 'out.electricity.total.energy_savings_intensity..kwh_per_ft2',
 'out.electricity.water_systems.energy_consumption_intensity..kwh_per_ft2',
 'out.electricity.water_systems.energy_savings_intensity..kwh_per_ft2',
 'out.emissions.electricity.aer_95_decarb_by_2035_from_2023..co2e_kg',
 'out.emissions.electricity.aer_95_decarb_by_2050_from_2023..co2e_kg',
 'out.emissions.electricity.aer_high_re_cost_from_2023..co2e_kg',
 'out.emissions.electricity.aer_low_re_cost_from_2023..co2e_kg',
 'out.emissions.electricity.aer_mid_case_from_2023..co2e_kg',
 'out.emissions.electricity.cooling.aer_95_decarb_by_2035_from_2023..co2e_kg',
 'out.emissions.electricity.cooling.aer_95_decarb_by_2050_from_2023..co2e_kg',
 'out.emissions.electricity.cooling.aer_high_re_cost_from_2023..co2e_kg',
 'out.emissions.electricity.cooling.aer_low_re_cost_from_2023..co2e_kg',
 'out.emissions.electricity.cooling.aer_mid_case_from_2023..co2e_kg',
 'out.emissions.electricity.cooling.egrid_2018_state..co2e_kg',
 'out.emissions.electricity.cooling.egrid_2018_subregion..co2e_kg',
 'out.emissions.electricity.cooling.egrid_2019_state..co2e_kg',
 'out.emissions.electricity.cooling.egrid_2019_subregion..co2e_kg',
 'out.emissions.electricity.cooling.egrid_2020_state..co2e_kg',
 'out.emissions.electricity.cooling.egrid_2020_subregion..co2e_kg',
 'out.emissions.electricity.cooling.egrid_2021_state..co2e_kg',
 'out.emissions.electricity.cooling.egrid_2021_subregion..co2e_kg',
 'out.emissions.electricity.cooling.lrmer_95_decarb_by_2035_15_2023_start..co2e_kg',
 'out.emissions.electricity.cooling.lrmer_95_decarb_by_2035_15_2025_start..co2e_kg',
 'out.emissions.electricity.cooling.lrmer_95_decarb_by_2035_25_2025_start..co2e_kg',
 'out.emissions.electricity.cooling.lrmer_95_decarb_by_2035_30_2023_start..co2e_kg',
 'out.emissions.electricity.cooling.lrmer_95_decarb_by_2050_15_2023_start..co2e_kg',
 'out.emissions.electricity.cooling.lrmer_95_decarb_by_2050_30_2023_start..co2e_kg',
 'out.emissions.electricity.cooling.lrmer_high_re_cost_15_2023_start..co2e_kg',
 'out.emissions.electricity.cooling.lrmer_high_re_cost_30_2023_start..co2e_kg',
 'out.emissions.electricity.cooling.lrmer_low_re_cost_15_2023_start..co2e_kg',
 'out.emissions.electricity.cooling.lrmer_low_re_cost_15_2025_start..co2e_kg',
 'out.emissions.electricity.cooling.lrmer_low_re_cost_25_2025_start..co2e_kg',
 'out.emissions.electricity.cooling.lrmer_low_re_cost_30_2023_start..co2e_kg',
 'out.emissions.electricity.cooling.lrmer_mid_case_15_2023_start..co2e_kg',
 'out.emissions.electricity.cooling.lrmer_mid_case_15_2025_start..co2e_kg',
 'out.emissions.electricity.cooling.lrmer_mid_case_25_2025_start..co2e_kg',
 'out.emissions.electricity.cooling.lrmer_mid_case_30_2023_start..co2e_kg',
 'out.emissions.electricity.egrid_2018_state..co2e_kg',
 'out.emissions.electricity.egrid_2018_subregion..co2e_kg',
 'out.emissions.electricity.egrid_2019_state..co2e_kg',
 'out.emissions.electricity.egrid_2019_subregion..co2e_kg',
 'out.emissions.electricity.egrid_2020_state..co2e_kg',
 'out.emissions.electricity.egrid_2020_subregion..co2e_kg',
 'out.emissions.electricity.egrid_2021_state..co2e_kg',
 'out.emissions.electricity.egrid_2021_subregion..co2e_kg',
 'out.emissions.electricity.enduse_group.hvac.aer_95_decarb_by_2035_from_2023..co2e_kg',
 'out.emissions.electricity.enduse_group.hvac.aer_95_decarb_by_2050_from_2023..co2e_kg',
 'out.emissions.electricity.enduse_group.hvac.aer_high_re_cost_from_2023..co2e_kg',
 'out.emissions.electricity.enduse_group.hvac.aer_low_re_cost_from_2023..co2e_kg',
 'out.emissions.electricity.enduse_group.hvac.aer_mid_case_from_2023..co2e_kg',
 'out.emissions.electricity.enduse_group.hvac.egrid_2018_state..co2e_kg',
 'out.emissions.electricity.enduse_group.hvac.egrid_2018_subregion..co2e_kg',
 'out.emissions.electricity.enduse_group.hvac.egrid_2019_state..co2e_kg',
 'out.emissions.electricity.enduse_group.hvac.egrid_2019_subregion..co2e_kg',
 'out.emissions.electricity.enduse_group.hvac.egrid_2020_state..co2e_kg',
 'out.emissions.electricity.enduse_group.hvac.egrid_2020_subregion..co2e_kg',
 'out.emissions.electricity.enduse_group.hvac.egrid_2021_state..co2e_kg',
 'out.emissions.electricity.enduse_group.hvac.egrid_2021_subregion..co2e_kg',
 'out.emissions.electricity.enduse_group.hvac.lrmer_95_decarb_by_2035_15_2023_start..co2e_kg',
 'out.emissions.electricity.enduse_group.hvac.lrmer_95_decarb_by_2035_15_2025_start..co2e_kg',
 'out.emissions.electricity.enduse_group.hvac.lrmer_95_decarb_by_2035_25_2025_start..co2e_kg',
 'out.emissions.electricity.enduse_group.hvac.lrmer_95_decarb_by_2035_30_2023_start..co2e_kg',
 'out.emissions.electricity.enduse_group.hvac.lrmer_95_decarb_by_2050_15_2023_start..co2e_kg',
 'out.emissions.electricity.enduse_group.hvac.lrmer_95_decarb_by_2050_30_2023_start..co2e_kg',
 'out.emissions.electricity.enduse_group.hvac.lrmer_high_re_cost_15_2023_start..co2e_kg',
 'out.emissions.electricity.enduse_group.hvac.lrmer_high_re_cost_30_2023_start..co2e_kg',
 'out.emissions.electricity.enduse_group.hvac.lrmer_low_re_cost_15_2023_start..co2e_kg',
 'out.emissions.electricity.enduse_group.hvac.lrmer_low_re_cost_15_2025_start..co2e_kg',
 'out.emissions.electricity.enduse_group.hvac.lrmer_low_re_cost_25_2025_start..co2e_kg',
 'out.emissions.electricity.enduse_group.hvac.lrmer_low_re_cost_30_2023_start..co2e_kg',
 'out.emissions.electricity.enduse_group.hvac.lrmer_mid_case_15_2023_start..co2e_kg',
 'out.emissions.electricity.enduse_group.hvac.lrmer_mid_case_15_2025_start..co2e_kg',
 'out.emissions.electricity.enduse_group.hvac.lrmer_mid_case_25_2025_start..co2e_kg',
 'out.emissions.electricity.enduse_group.hvac.lrmer_mid_case_30_2023_start..co2e_kg',
 'out.emissions.electricity.exterior_lights.aer_95_decarb_by_2035_from_2023..co2e_kg',
 'out.emissions.electricity.exterior_lights.aer_95_decarb_by_2050_from_2023..co2e_kg',
 'out.emissions.electricity.exterior_lights.aer_high_re_cost_from_2023..co2e_kg',
 'out.emissions.electricity.exterior_lights.aer_low_re_cost_from_2023..co2e_kg',
 'out.emissions.electricity.exterior_lights.aer_mid_case_from_2023..co2e_kg',
 'out.emissions.electricity.exterior_lights.egrid_2018_state..co2e_kg',
 'out.emissions.electricity.exterior_lights.egrid_2018_subregion..co2e_kg',
 'out.emissions.electricity.exterior_lights.egrid_2019_state..co2e_kg',
 'out.emissions.electricity.exterior_lights.egrid_2019_subregion..co2e_kg',
 'out.emissions.electricity.exterior_lights.egrid_2020_state..co2e_kg',
 'out.emissions.electricity.exterior_lights.egrid_2020_subregion..co2e_kg',
 'out.emissions.electricity.exterior_lights.egrid_2021_state..co2e_kg',
 'out.emissions.electricity.exterior_lights.egrid_2021_subregion..co2e_kg',
 'out.emissions.electricity.exterior_lights.lrmer_95_decarb_by_2035_15_2023_start..co2e_kg',
 'out.emissions.electricity.exterior_lights.lrmer_95_decarb_by_2035_15_2025_start..co2e_kg',
 'out.emissions.electricity.exterior_lights.lrmer_95_decarb_by_2035_25_2025_start..co2e_kg',
 'out.emissions.electricity.exterior_lights.lrmer_95_decarb_by_2035_30_2023_start..co2e_kg',
 'out.emissions.electricity.exterior_lights.lrmer_95_decarb_by_2050_15_2023_start..co2e_kg',
 'out.emissions.electricity.exterior_lights.lrmer_95_decarb_by_2050_30_2023_start..co2e_kg',
 'out.emissions.electricity.exterior_lights.lrmer_high_re_cost_15_2023_start..co2e_kg',
 'out.emissions.electricity.exterior_lights.lrmer_high_re_cost_30_2023_start..co2e_kg',
 'out.emissions.electricity.exterior_lights.lrmer_low_re_cost_15_2023_start..co2e_kg',
 'out.emissions.electricity.exterior_lights.lrmer_low_re_cost_15_2025_start..co2e_kg',
 'out.emissions.electricity.exterior_lights.lrmer_low_re_cost_25_2025_start..co2e_kg',
 'out.emissions.electricity.exterior_lights.lrmer_low_re_cost_30_2023_start..co2e_kg',
 'out.emissions.electricity.exterior_lights.lrmer_mid_case_15_2023_start..co2e_kg',
 'out.emissions.electricity.exterior_lights.lrmer_mid_case_15_2025_start..co2e_kg',
 'out.emissions.electricity.exterior_lights.lrmer_mid_case_25_2025_start..co2e_kg',
 'out.emissions.electricity.exterior_lights.lrmer_mid_case_30_2023_start..co2e_kg',
 'out.emissions.electricity.heating.aer_95_decarb_by_2035_from_2023..co2e_kg',
 'out.emissions.electricity.heating.aer_95_decarb_by_2050_from_2023..co2e_kg',
 'out.emissions.electricity.heating.aer_high_re_cost_from_2023..co2e_kg',
 'out.emissions.electricity.heating.aer_low_re_cost_from_2023..co2e_kg',
 'out.emissions.electricity.heating.aer_mid_case_from_2023..co2e_kg',
 'out.emissions.electricity.heating.egrid_2018_state..co2e_kg',
 'out.emissions.electricity.heating.egrid_2018_subregion..co2e_kg',
 'out.emissions.electricity.heating.egrid_2019_state..co2e_kg',
 'out.emissions.electricity.heating.egrid_2019_subregion..co2e_kg',
 'out.emissions.electricity.heating.egrid_2020_state..co2e_kg',
 'out.emissions.electricity.heating.egrid_2020_subregion..co2e_kg',
 'out.emissions.electricity.heating.egrid_2021_state..co2e_kg',
 'out.emissions.electricity.heating.egrid_2021_subregion..co2e_kg',
 'out.emissions.electricity.heating.lrmer_95_decarb_by_2035_15_2023_start..co2e_kg',
 'out.emissions.electricity.heating.lrmer_95_decarb_by_2035_15_2025_start..co2e_kg',
 'out.emissions.electricity.heating.lrmer_95_decarb_by_2035_25_2025_start..co2e_kg',
 'out.emissions.electricity.heating.lrmer_95_decarb_by_2035_30_2023_start..co2e_kg',
 'out.emissions.electricity.heating.lrmer_95_decarb_by_2050_15_2023_start..co2e_kg',
 'out.emissions.electricity.heating.lrmer_95_decarb_by_2050_30_2023_start..co2e_kg',
 'out.emissions.electricity.heating.lrmer_high_re_cost_15_2023_start..co2e_kg',
 'out.emissions.electricity.heating.lrmer_high_re_cost_30_2023_start..co2e_kg',
 'out.emissions.electricity.heating.lrmer_low_re_cost_15_2023_start..co2e_kg',
 'out.emissions.electricity.heating.lrmer_low_re_cost_15_2025_start..co2e_kg',
 'out.emissions.electricity.heating.lrmer_low_re_cost_25_2025_start..co2e_kg',
 'out.emissions.electricity.heating.lrmer_low_re_cost_30_2023_start..co2e_kg',
 'out.emissions.electricity.heating.lrmer_mid_case_15_2023_start..co2e_kg',
 'out.emissions.electricity.heating.lrmer_mid_case_15_2025_start..co2e_kg',
 'out.emissions.electricity.heating.lrmer_mid_case_25_2025_start..co2e_kg',
 'out.emissions.electricity.heating.lrmer_mid_case_30_2023_start..co2e_kg',
 'out.emissions.electricity.interior_equipment.aer_95_decarb_by_2035_from_2023..co2e_kg',
 'out.emissions.electricity.interior_equipment.aer_95_decarb_by_2050_from_2023..co2e_kg',
 'out.emissions.electricity.interior_equipment.aer_high_re_cost_from_2023..co2e_kg',
 'out.emissions.electricity.interior_equipment.aer_low_re_cost_from_2023..co2e_kg',
 'out.emissions.electricity.interior_equipment.aer_mid_case_from_2023..co2e_kg',
 'out.emissions.electricity.interior_equipment.egrid_2018_state..co2e_kg',
 'out.emissions.electricity.interior_equipment.egrid_2018_subregion..co2e_kg',
 'out.emissions.electricity.interior_equipment.egrid_2019_state..co2e_kg',
 'out.emissions.electricity.interior_equipment.egrid_2019_subregion..co2e_kg',
 'out.emissions.electricity.interior_equipment.egrid_2020_state..co2e_kg',
 'out.emissions.electricity.interior_equipment.egrid_2020_subregion..co2e_kg',
 'out.emissions.electricity.interior_equipment.egrid_2021_state..co2e_kg',
 'out.emissions.electricity.interior_equipment.egrid_2021_subregion..co2e_kg',
 'out.emissions.electricity.interior_equipment.lrmer_95_decarb_by_2035_15_2023_start..co2e_kg',
 'out.emissions.electricity.interior_equipment.lrmer_95_decarb_by_2035_15_2025_start..co2e_kg',
 'out.emissions.electricity.interior_equipment.lrmer_95_decarb_by_2035_25_2025_start..co2e_kg',
 'out.emissions.electricity.interior_equipment.lrmer_95_decarb_by_2035_30_2023_start..co2e_kg',
 'out.emissions.electricity.interior_equipment.lrmer_95_decarb_by_2050_15_2023_start..co2e_kg',
 'out.emissions.electricity.interior_equipment.lrmer_95_decarb_by_2050_30_2023_start..co2e_kg',
 'out.emissions.electricity.interior_equipment.lrmer_high_re_cost_15_2023_start..co2e_kg',
 'out.emissions.electricity.interior_equipment.lrmer_high_re_cost_30_2023_start..co2e_kg',
 'out.emissions.electricity.interior_equipment.lrmer_low_re_cost_15_2023_start..co2e_kg',
 'out.emissions.electricity.interior_equipment.lrmer_low_re_cost_15_2025_start..co2e_kg',
 'out.emissions.electricity.interior_equipment.lrmer_low_re_cost_25_2025_start..co2e_kg',
 'out.emissions.electricity.interior_equipment.lrmer_low_re_cost_30_2023_start..co2e_kg',
 'out.emissions.electricity.interior_equipment.lrmer_mid_case_15_2023_start..co2e_kg',
 'out.emissions.electricity.interior_equipment.lrmer_mid_case_15_2025_start..co2e_kg',
 'out.emissions.electricity.interior_equipment.lrmer_mid_case_25_2025_start..co2e_kg',
 'out.emissions.electricity.interior_equipment.lrmer_mid_case_30_2023_start..co2e_kg',
 'out.emissions.electricity.interior_lights.aer_95_decarb_by_2035_from_2023..co2e_kg',
 'out.emissions.electricity.interior_lights.aer_95_decarb_by_2050_from_2023..co2e_kg',
 'out.emissions.electricity.interior_lights.aer_high_re_cost_from_2023..co2e_kg',
 'out.emissions.electricity.interior_lights.aer_low_re_cost_from_2023..co2e_kg',
 'out.emissions.electricity.interior_lights.aer_mid_case_from_2023..co2e_kg',
 'out.emissions.electricity.interior_lights.egrid_2018_state..co2e_kg',
 'out.emissions.electricity.interior_lights.egrid_2018_subregion..co2e_kg',
 'out.emissions.electricity.interior_lights.egrid_2019_state..co2e_kg',
 'out.emissions.electricity.interior_lights.egrid_2019_subregion..co2e_kg',
 'out.emissions.electricity.interior_lights.egrid_2020_state..co2e_kg',
 'out.emissions.electricity.interior_lights.egrid_2020_subregion..co2e_kg',
 'out.emissions.electricity.interior_lights.egrid_2021_state..co2e_kg',
 'out.emissions.electricity.interior_lights.egrid_2021_subregion..co2e_kg',
 'out.emissions.electricity.interior_lights.lrmer_95_decarb_by_2035_15_2023_start..co2e_kg',
 'out.emissions.electricity.interior_lights.lrmer_95_decarb_by_2035_15_2025_start..co2e_kg',
 'out.emissions.electricity.interior_lights.lrmer_95_decarb_by_2035_25_2025_start..co2e_kg',
 'out.emissions.electricity.interior_lights.lrmer_95_decarb_by_2035_30_2023_start..co2e_kg',
 'out.emissions.electricity.interior_lights.lrmer_95_decarb_by_2050_15_2023_start..co2e_kg',
 'out.emissions.electricity.interior_lights.lrmer_95_decarb_by_2050_30_2023_start..co2e_kg',
 'out.emissions.electricity.interior_lights.lrmer_high_re_cost_15_2023_start..co2e_kg',
 'out.emissions.electricity.interior_lights.lrmer_high_re_cost_30_2023_start..co2e_kg',
 'out.emissions.electricity.interior_lights.lrmer_low_re_cost_15_2023_start..co2e_kg',
 'out.emissions.electricity.interior_lights.lrmer_low_re_cost_15_2025_start..co2e_kg',
 'out.emissions.electricity.interior_lights.lrmer_low_re_cost_25_2025_start..co2e_kg',
 'out.emissions.electricity.interior_lights.lrmer_low_re_cost_30_2023_start..co2e_kg',
 'out.emissions.electricity.interior_lights.lrmer_mid_case_15_2023_start..co2e_kg',
 'out.emissions.electricity.interior_lights.lrmer_mid_case_15_2025_start..co2e_kg',
 'out.emissions.electricity.interior_lights.lrmer_mid_case_25_2025_start..co2e_kg',
 'out.emissions.electricity.interior_lights.lrmer_mid_case_30_2023_start..co2e_kg',
 'out.emissions.electricity.lrmer_95_decarb_by_2035_15_2023_start..co2e_kg',
 'out.emissions.electricity.lrmer_95_decarb_by_2035_15_2025_start..co2e_kg',
 'out.emissions.electricity.lrmer_95_decarb_by_2035_25_2025_start..co2e_kg',
 'out.emissions.electricity.lrmer_95_decarb_by_2035_30_2023_start..co2e_kg',
 'out.emissions.electricity.lrmer_95_decarb_by_2050_15_2023_start..co2e_kg',
 'out.emissions.electricity.lrmer_95_decarb_by_2050_30_2023_start..co2e_kg',
 'out.emissions.electricity.lrmer_high_re_cost_15_2023_start..co2e_kg',

In [12]:
df.select(pl.col('in.county_name').unique())[:10].collect()

shape: (10, 1)
┌─────────────────────────┐
│ in.county_name          │
│ ---                     │
│ str                     │
╞═════════════════════════╡
│ TX, Frio County         │
│ MS, Lowndes County      │
│ MO, Cooper County       │
│ WI, Winnebago County    │
│ IL, Cook County         │
│ MS, Lafayette County    │
│ OR, Wasco County        │
│ VA, Accomack County     │
│ VA, King William County │
│ AR, Arkansas County     │
└─────────────────────────┘

In [13]:
result = my_run.query(
    enduses=["out.electricity.total.energy_consumption..kwh"],
    restrict=[("in.county_name", "MN, Lyon County"), ("state", "MN")],
    annual_only=True,
    upgrade_id=1,
    get_query_only=True,
    applied_only=False
)
print(result)

WARNING:buildstock_query.query_core:Column in.county_name found in multiple tables ['baseline', 'upgrade']. Using baseline
WARNING:buildstock_query.query_core:Column state found in multiple tables ['baseline', 'upgrade', 'comstock_amy2018_r2_2025_ts_by_state']. Using baseline

SELECT sum(1) AS sample_count, sum(baseline.weight) AS units_count, sum(CASE WHEN (CAST(upgrade.applicability AS VARCHAR) = 'true') THEN upgrade."out.electricity.total.energy_consumption..kwh" ELSE baseline."out.electricity.total.energy_consumption..kwh" END * baseline.weight) AS "electricity.total.energy_consumption..kwh"
FROM (SELECT *
FROM comstock_amy2018_r2_2025_md_by_state_and_county_parquet
WHERE CAST(comstock_amy2018_r2_2025_md_by_state_and_county_parquet.upgrade AS VARCHAR) = '0') AS baseline LEFT OUTER JOIN (SELECT *
FROM comstock_amy2018_r2_2025_md_by_state_and_county_parquet
WHERE CAST(comstock_amy2018_r2_2025_md_by_state_and_county_parquet.upgrade AS VARCHAR) != '0') AS upgrade ON baseline.bldg_id = upgrade.bldg_id AND baseline."in.nhgis_tract_gisjoin" = upgrade."in.nhgis_tract_gisjoin" AND baseline.state = upgrade.state AND CAST(upgrade.upgrade AS VARCHAR) = '1' AND CAST(upgrade.applicability AS VARCHAR) = 'true'
WHERE CAST(baseline.applicability AS VARCHAR) = 'true' AND baseline."in.county_name" = 'MN, Lyon County' AND baseline.state = 'MN'

In [14]:
# Query the total electricity for a county
my_run.query(
    enduses=["out.electricity.total.energy_consumption..kwh"],
    restrict=[("in.county_name", "MN, Lyon County"), ("state", "MN")],
    annual_only=True,
    upgrade_id=0
)

WARNING:buildstock_query.query_core:Column in.county_name found in multiple tables ['baseline', 'upgrade']. Using baseline
WARNING:buildstock_query.query_core:Column state found in multiple tables ['baseline', 'upgrade', 'comstock_amy2018_r2_2025_ts_by_state']. Using baseline

INFO:botocore.tokens:Loading cached SSO token for nrel-sso

   sample_count  units_count  electricity.total.energy_consumption..kwh
0           316   150.900996                               3.527991e+07

In [15]:
elec_total_df = df.filter(
    (pl.col("in.county_name") == "MN, Lyon County") & (pl.col("state") == "MN")
).select(pl.col('bldg_id').n_unique().alias("unique_bldg_count"),
         pl.len().alias('sample_count'),
         pl.sum('weight').alias('units_count'), 
         (pl.col("out.electricity.total.energy_consumption..kwh") * pl.col("weight")).sum()
         ).collect()
elec_total_df

shape: (1, 4)
┌───────────────────┬──────────────┬─────────────┬─────────────────────────────────┐
│ unique_bldg_count ┆ sample_count ┆ units_count ┆ out.electricity.total.energy_c… │
│ ---               ┆ ---          ┆ ---         ┆ ---                             │
│ u32               ┆ u32          ┆ f64         ┆ f64                             │
╞═══════════════════╪══════════════╪═════════════╪═════════════════════════════════╡
│ 218               ┆ 316          ┆ 150.900996  ┆ 3.5280e7                        │
└───────────────────┴──────────────┴─────────────┴─────────────────────────────────┘

In [16]:
# Query the total electricity for a county
my_run.query(
    enduses=["out.electricity.total.energy_consumption..kwh"],
    restrict=[("in.county_name", "MN, Lyon County"), ("state", "MN")],
    annual_only=True,
    include_baseline=True,
    applied_only=False,
    upgrade_id=1
)

WARNING:buildstock_query.query_core:Column in.county_name found in multiple tables ['baseline', 'upgrade']. Using baseline
WARNING:buildstock_query.query_core:Column state found in multiple tables ['baseline', 'upgrade', 'comstock_amy2018_r2_2025_ts_by_state']. Using baseline

,sample_count,units_count,electricity.total.energy_consumption..kwh__baseline,electricity.total.energy_consumption..kwh__upgrade
0,316,150.900996,3.527991e+07,3.761094e+07

In [17]:
my_run.query(
    enduses=["out.electricity.total.energy_consumption..kwh"],
    restrict=[("in.county_name", "MN, Lyon County"), ("state", "MN")],
    annual_only=True,
    include_baseline=True,
    applied_only=True,
    upgrade_id=1
)

WARNING:buildstock_query.query_core:Column in.county_name found in multiple tables ['baseline', 'upgrade']. Using baseline
WARNING:buildstock_query.query_core:Column state found in multiple tables ['baseline', 'upgrade', 'comstock_amy2018_r2_2025_ts_by_state']. Using baseline

,sample_count,units_count,electricity.total.energy_consumption..kwh__baseline,electricity.total.energy_consumption..kwh__upgrade
0,183,77.074284,1.316137e+07,1.549240e+07

In [ ]:
applied_filter = my_run.get_applied_buildings_filter(all_of=[1, 12, 13])
my_run.query(
    enduses=["out.electricity.total.energy_consumption..kwh"],
    restrict=[applied_filter, ("in.county_name", "MN, Lyon County"), ("state", "MN")],
    annual_only=True,
    include_baseline=True,
    applied_only=True,
    upgrade_id=1
)

In [ ]:
applied_filter = my_run.get_applied_buildings_filter(all_of=[1, 12, 13])
my_run.query(
    enduses=["out.electricity.total.energy_consumption"],
    restrict=[applied_filter, ("in.county_name", "MN, Lyon County"), ("state", "MN")],
    annual_only=False,
    include_baseline=True,
    applied_only=True,
    upgrade_id=1
)